title: Xwarewallet EBIS
logo: /assets/img/logo.png
description: EbiS Environmental Blockchain Incentive Solution.
show_downloads: true  
google_analytics: wooriapt79
theme: jekyll-theme-minimal

# Site Author
author:
  name: Blockchain Lab
  avatar: Lab
  bio: Your biography for the left-hand sidebar
  location: Korea
