title: XWareWallet
logo: /assets/img/681890f1971b8416cedaf51efe35e351.jpg
description: Directory of ERC20 token images. Upload yours to get displayed in the XwareWallet
show_downloads: true  
google_analytics: wooriapt79
theme: jekyll-theme-minimal

# Site Author
author:
  name: Blockchain Lab
  avatar: Lab
  bio: Your biography for the left-hand sidebar
  location: Korea
