title: Xwarewallet EBIS
logo: /assets/img/Logo-Chain.jpg
description:  EbiS 환경활동 보상 시스템
show_downloads: true  
google_analytics: wooriapt79
theme: jekyll-theme-minimal

# Site Author
author:
  name: Blockchain Lab
  avatar: Lab
  bio: Your biography for the left-hand sidebar
  location: Korea
