title: XWareWallet
logo: /assets/img/android-chrome-256x256.png
description: Directory of ERC20 token images.XwareWallet
show_downloads: true  
google_analytics: wooriapt79
theme: jekyll-theme-minimal

# Site Author
author:
  name: Blockchain Lab
  avatar: Lab
  bio: Your biography for the left-hand sidebar
  location: Korea
